apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: http-server
  namespace: default
spec:
  template:
    spec:
      runtimeClassName: wasmedge-v1
      timeoutSeconds: 1
      containers:
        - name: http-server
          image: { will be replaced by deployment script }
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
