apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: wasmwasi-dapr-rs
  namespace: default
spec:
  template:
    metadata:
      annotations:
        module.wasm.image/variant: compat-smart
    spec:
      runtimeClassName: wasmedge-v1
      timeoutSeconds: 1
      containers:
        - name: http-server
          image: kw6e61040aacr.azurecr.io/warpwasi-dapr-rs:1711727994
          ports:
            - containerPort: 8080
              protocol: TCP
          livenessProbe:
            tcpSocket:
              port: 8080
