apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  secretTargetRef:
    - key: connectionString
      name: servicebus-secret
      parameter: connection
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-ingress-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: distributor
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-ingress-spin
        messageCount: "100"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-express-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: receiver-express
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-express-spin
        messageCount: "100"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-standard-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: receiver-standard
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 1
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-standard-spin
        messageCount: "100"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "distributor"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
        dapr.io/enable-api-logging: "true"
        dapr.io/enable-app-health-check: "true"
        dapr.io/log-level: "info"
        dapr.io/app-protocol: "http"
        dapr.io/placement-host-address: ""
        dapr.io/sidecar-listen-addresses: "0.0.0.0,[::]"
    spec:
      runtimeClassName: wasmtime-spin-v2
      nodeSelector:
        agentpool: backend
      containers:
        - name: distributor
          image: { will be replaced by deployment script }
          command: ["/"]
          env:
            - name: SPIN_VARIABLE_DAPR_URL
              value: "http://localhost:3500"
          livenessProbe:
            httpGet:
              path: .well-known/spin/health
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-express
  template:
    metadata:
      labels:
        app: receiver-express
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "receiver-express"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
        dapr.io/enable-api-logging: "true"
        dapr.io/enable-app-health-check: "true"
        dapr.io/log-level: "info"
        dapr.io/app-protocol: "http"
        dapr.io/placement-host-address: ""
        dapr.io/sidecar-listen-addresses: "0.0.0.0,[::]"
    spec:
      runtimeClassName: wasmtime-spin-v2
      nodeSelector:
        agentpool: backend
      containers:
        - name: receiver-express
          image: { will be replaced by deployment script }
          command: ["/"]
          env:
            - name: SPIN_VARIABLE_DAPR_URL
              value: "http://localhost:3500"
          livenessProbe:
            httpGet:
              path: .well-known/spin/health
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-standard
  template:
    metadata:
      labels:
        app: receiver-standard
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "receiver-standard"
        dapr.io/app-port: "80"
        dapr.io/config: "appconfig"
        dapr.io/enable-api-logging: "true"
        dapr.io/enable-app-health-check: "true"
        dapr.io/log-level: "info"
        dapr.io/app-protocol: "http"
        dapr.io/placement-host-address: ""
        dapr.io/sidecar-listen-addresses: "0.0.0.0,[::]"
    spec:
      runtimeClassName: wasmtime-spin-v2
      nodeSelector:
        agentpool: backend
      containers:
        - name: receiver-standard
          image: { will be replaced by deployment script }
          command: ["/"]
          env:
            - name: SPIN_VARIABLE_DAPR_URL
              value: "http://localhost:3500"
          livenessProbe:
            httpGet:
              path: .well-known/spin/health
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: distributor-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dapr
      protocol: TCP
      port: 3500
      targetPort: 3500
  selector:
    app: distributor
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-express-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dapr
      protocol: TCP
      port: 3500
      targetPort: 3500
  selector:
    app: receiver-express
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-standard-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
    - name: dapr
      protocol: TCP
      port: 3500
      targetPort: 3500
  selector:
    app: receiver-standard
