FROM rust:latest AS builder
WORKDIR /app

COPY Cargo.toml .
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build --release

COPY src src
RUN touch src/main.rs
RUN cargo build --release

# RUN strip target/release/warp-dapr-rs

FROM alpine:latest as release
WORKDIR /app
COPY --from=builder /app/target/release/* .

EXPOSE 8080

CMD ["./warp-dapr-rs"]
