apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
    spec:
      runtimeClassName: wasmtime-spin-v2
      containers:
        - name: distributor
          image: { will be replaced by deployment script }
          command: ["/"]
          env:
            - name: SPIN_VARIABLE_DAPR_URL
              value: "http://distributor-dapr"
            - name: RUST_BACKTRACK
              value: "1"
          livenessProbe:
            httpGet:
              path: .well-known/spin/health
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: distributor-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: distributor
