apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: secretstore
spec:
  type: secretstores.kubernetes
  version: v1
  metadata: []
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: q-order-ingress
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-secret
        key: connectionString
    - name: queueName
      value: q-order-ingress-spin
    - name: maxBulkSubCount
      value: 100
    - name: maxActiveMessages
      value: 1000
    - name: maxConcurrentHandlers
      value: 8
auth:
  secretStore: secretstore
scopes:
  - distributor
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: q-order-express-out
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-secret
        key: connectionString
    - name: queueName
      value: q-order-express-spin
    - name: direction
      value: output
auth:
  secretStore: secretstore
scopes:
  - distributor
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: q-order-standard-out
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-secret
        key: connectionString
    - name: queueName
      value: q-order-standard-spin
    - name: direction
      value: output
auth:
  secretStore: secretstore
scopes:
  - distributor
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: q-order-express-in
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-secret
        key: connectionString
    - name: queueName
      value: q-order-express-spin
    - name: direction
      value: input
    - name: maxBulkSubCount
      value: 100
    - name: maxActiveMessages
      value: 1000
    - name: maxConcurrentHandlers
      value: 8
auth:
  secretStore: secretstore
scopes:
  - receiver-express
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: q-order-standard-in
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
    - name: connectionString
      secretKeyRef:
        name: servicebus-secret
        key: connectionString
    - name: queueName
      value: q-order-standard-spin
    - name: direction
      value: input
    - name: maxBulkSubCount
      value: 100
    - name: maxActiveMessages
      value: 1000
    - name: maxConcurrentHandlers
      value: 8
auth:
  secretStore: secretstore
scopes:
  - receiver-standard
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: express-outbox
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
    - name: accountName
      secretKeyRef:
        name: storage-secret
        key: accountName
    - name: accountKey
      secretKeyRef:
        name: storage-secret
        key: accountKey
    - name: containerName
      value: express-outbox
auth:
  secretStore: secretstore
scopes:
  - receiver-express
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: standard-outbox
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
    - name: accountName
      secretKeyRef:
        name: storage-secret
        key: accountName
    - name: accountKey
      secretKeyRef:
        name: storage-secret
        key: accountKey
    - name: containerName
      value: standard-outbox
auth:
  secretStore: secretstore
scopes:
  - receiver-standard
