apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  name: azure-servicebus-auth
spec:
  secretTargetRef:
    - key: connectionString
      name: servicebus-secret
      parameter: connection
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-ingress-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: distributor
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-ingress-spin
        messageCount: "100"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-ingress-dapr-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: distributor-dapr
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-ingress-spin
        messageCount: "1000"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-express-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: receiver-express
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-express-spin
        messageCount: "100"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-express-dapr-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: receiver-express-dapr
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-express-spin
        messageCount: "1000"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-standard-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: receiver-standard
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-standard-spin
        messageCount: "100"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: order-standard-dapr-scaledobject
  namespace: default
spec:
  scaleTargetRef:
    kind: Deployment
    name: receiver-standard-dapr
  pollingInterval: 10
  cooldownPeriod: 60
  minReplicaCount: 0
  maxReplicaCount: 20
  triggers:
    - type: azure-servicebus
      metadata:
        queueName: q-order-standard-spin
        messageCount: "1000"
      authenticationRef:
        name: azure-servicebus-auth
---
apiVersion: core.spinoperator.dev/v1
kind: SpinApp
metadata:
  name: distributor
spec:
  image: { will be replaced by deployment script }
  executor: containerd-shim-spin
  enableAutoscaling: true
  deploymentAnnotations:
    scheduler.alpha.kubernetes.io/node-selector: agentpool=wasm
  variables:
    - name: dapr_url
      value: "http://distributor-dapr:3500"
---
apiVersion: core.spinoperator.dev/v1
kind: SpinApp
metadata:
  name: receiver-express
spec:
  image: { will be replaced by deployment script }
  executor: containerd-shim-spin
  enableAutoscaling: true
  deploymentAnnotations:
    scheduler.alpha.kubernetes.io/node-selector: agentpool=wasm
  variables:
    - name: dapr_url
      value: "http://receiver-express-dapr:3500"
---
apiVersion: core.spinoperator.dev/v1
kind: SpinApp
metadata:
  name: receiver-standard
spec:
  image: { will be replaced by deployment script }
  executor: containerd-shim-spin
  enableAutoscaling: true
  deploymentAnnotations:
    scheduler.alpha.kubernetes.io/node-selector: agentpool=wasm
  variables:
    - name: dapr_url
      value: "http://receiver-standard-dapr:3500"
