apiVersion: approuting.kubernetes.azure.com/v1alpha1
kind: NginxIngressController
metadata:
  name: nginx-internal
spec:
  ingressClassName: nginx-internal
  controllerNamePrefix: nginx-internal
  loadBalancerAnnotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: internal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    nginx.ingress.kubernetes.io/use-regex: "true"
spec:
  ingressClassName: nginx-internal
  rules:
    - http:
        paths:
          - path: /distributor(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: distributor-svc
                port:
                  number: 80
    - http:
        paths:
          - path: /receiver-express(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: receiver-express-svc
                port:
                  number: 80
    - http:
        paths:
          - path: /receiver-standard(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: receiver-standard-svc
                port:
                  number: 80
# ---
# kind: HTTPScaledObject
# apiVersion: http.keda.sh/v1alpha1
# metadata:
#   name: order-ingress-scaledobject
#   namespace: default
# spec:
#   hosts:
#     - distributor-svc.default.svc.cluster.local
#   pathPrefixes:
#     - "/"
#   targetPendingRequests: 200
#   scaleTargetRef:
#     name: distributor
#     kind: Deployment
#     apiVersion: apps/v1
#     service: distributor-svc
#     port: 80
#   replicas:
#     min: 1
#     max: 30
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: distributor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: distributor
  template:
    metadata:
      labels:
        app: distributor
    spec:
      nodeSelector:
        agentpool: classic
      containers:
        - name: distributor
          image: { will be replaced by deployment script }
          env:
            - name: DAPR_HTTP_HOST
              value: "distributor-dapr"
            - name: PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: healthz
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-express
  template:
    metadata:
      labels:
        app: receiver-express
    spec:
      nodeSelector:
        agentpool: classic
      containers:
        - name: receiver-express
          image: { will be replaced by deployment script }
          env:
            - name: DAPR_HTTP_HOST
              value: "receiver-express-dapr"
            - name: PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: healthz
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-standard
spec:
  replicas: 1
  selector:
    matchLabels:
      app: receiver-standard
  template:
    metadata:
      labels:
        app: receiver-standard
    spec:
      nodeSelector:
        agentpool: classic
      containers:
        - name: receiver-standard
          image: { will be replaced by deployment script }
          env:
            - name: DAPR_HTTP_HOST
              value: "receiver-standard-dapr"
            - name: PORT
              value: "80"
          livenessProbe:
            httpGet:
              path: healthz
              port: 80
            initialDelaySeconds: 45
            periodSeconds: 3
---
apiVersion: v1
kind: Service
metadata:
  name: distributor-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: distributor
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-express-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: receiver-express
---
apiVersion: v1
kind: Service
metadata:
  name: receiver-standard-svc
spec:
  type: ClusterIP
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 80
  selector:
    app: receiver-standard
