apiVersion: v1
kind: Namespace
metadata:
  name: frontend
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: agentpool=default
spec: {}
status: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
  annotations:
    scheduler.alpha.kubernetes.io/node-selector: agentpool=backend
spec: {}
status: {}
